# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target "SampleApp" do
  pod "QuickDialog/Core", :path => "../"
  pod "QuickDialog/Forms", :path => "../"
  pod "QuickDialog/Extras", :path => "../"
end

